version: '3'
services:
  mssql:
    image: "microsoft/mssql-server-linux"
    # restart: always
    volumes:
      - dbsql-data:/var/opt/mssql
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: '@SQLserverpa55'
      MSSQL_PID: 'Express'
    networks:
      - task-network

networks:
  task-network:
    driver: bridge

volumes:
  dbsql-data: